# General cluster parameters.
# https://deckhouse.io/documentation/v1/installing/configuration.html#clusterconfiguration
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Cloud
cloud:
  provider: AWS
  prefix: "example"
# Address space of the cluster's Pods.
podSubnetCIDR: 11.11.0.0/16
# Address space of the cluster's services.
serviceSubnetCIDR: 11.11.0.0/16
kubernetesVersion: "1.26"
clusterDomain: "cluster.local"
---
# Section for bootstrapping the Deckhouse cluster.
# https://deckhouse.io/documentation/v1/installing/configuration.html#initconfiguration
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  releaseChannel: Stable
  configOverrides:
    global:
      modules:
        # Template that will be used for system apps domains within the cluster, it is hard to be changed after installation, so check it twice.
        publicDomainTemplate: "%s.cluster.example.com"
    userAuthn:
      controlPlaneConfigurator:
        dexCAMode: DoNotNeed
      publishAPI:
        enable: true
        https:
          mode: Global
---
# Section containing the parameters of the cloud provider.
# https://deckhouse.io/documentation/v1/modules/030-cloud-provider-aws/cluster_configuration.html
apiVersion: deckhouse.io/v1
kind: AWSClusterConfiguration
layout: WithoutNAT
# AWS EC2 access parameters.
provider:
  providerAccessKeyId: xxx
  providerSecretAccessKey: xxx
  region: xx-xx-1
masterNodeGroup:
  replicas: 1
  instanceClass:
    # Master node VM disk size
    diskSizeGb: 30
    # Master node VM disk type
    diskType: gp2
    # Master node instance type
    instanceType: t3a.xlarge
    # Amazon Machine Image ID.
    # The example uses the Ubuntu Server 22.04 image for the 'eu-central-1' region.
    # Change the AMI ID if you use a different region (the 'provider.region' parameter).
    # AMI Catalog in the AWS console: EC2 -> AMI Catalog.
    ami: ami-xxxxxx
# Address space of the AWS cloud.
vpcNetworkCIDR: "11.11.0.0/16"
# Address space of the cluster's nodes.
nodeNetworkCIDR: "11.11.32.0/20"
# Public SSH key for accessing cloud nodes.
# This key will be added to the user on created nodes (the username depends on the image used).
sshPublicKey: ssh-rsa xxxxxxxxx== l7-aws
