# Section containing the parameters of instance class for worker nodes.
# https://deckhouse.io/documentation/v1/modules/030-cloud-provider-aws/cr.html
apiVersion: deckhouse.io/v1
kind: AWSInstanceClass
metadata:
  name: worker
spec:
  # VM disk size.
  # You might consider changing this.
  diskSizeGb: 60
  # VM disk type to use.
  # You might consider changing this.
  diskType: gp3
  # Type of the instance.
  # You might consider changing this.
  instanceType: c5a.xlarge
---
# Section containing the parameters of worker node group.
# https://deckhouse.io/documentation/v1/modules/040-node-manager/cr.html#nodegroup
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker
spec:
  cloudInstances:
    classReference:
      kind: AWSInstanceClass
      name: worker
    # The maximum number of instances for the group in each zone (used by the autoscaling).
    # You might consider changing this.
    maxPerZone: 3
    # The minimum number of instances for the group in each zone.
    minPerZone: 1
    # List of availability zones to create instances in.
    # You might consider changing this.
    zones:
      - us-west-2a
  disruptions:
    approvalMode: Automatic
  nodeType: CloudEphemeral
---
# Section containing the parameters of Nginx Ingress controller.
# https://deckhouse.io/documentation/v1/modules/402-ingress-nginx/cr.html
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: nginx
spec:
  ingressClass: nginx
  inlet: LoadBalancer
  loadBalancer:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
  # Describes on which nodes the Ingress Controller will be located. Label node.deckhouse.io/group: <NAME_GROUP_NAME> is set automatically.
  nodeSelector:
    node.deckhouse.io/group: worker
---
# RBAC and authorization settings.
# https://deckhouse.io/documentation/v1/modules/140-user-authz/cr.html#clusterauthorizationrule
apiVersion: deckhouse.io/v1
kind: ClusterAuthorizationRule
metadata:
  name: admin
spec:
  subjects:
    - kind: User
      name: user@example.com
  accessLevel: SuperAdmin
  portForwarding: true
---
# Parameters of the static user.
# https://deckhouse.io/documentation/v1/modules/150-user-authn/cr.html#user
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: admin
spec:
  # User e-mail.
  email: user@example.com
  # User password hash generated as:
  # echo "<PASSWORD>" | htpasswd -BinC 10 "" | cut -d: -f2
  password: ''
